#!/usr/bin/env swift
import Foundation

// Generates a committed Swift "code version" of a Pages template package.
//
// Reads a .pages document (a Zip) and emits a Swift source file that embeds every
// package entry as base64 — so `SwiftTextPages` can write documents from scratch
// with nothing bundled at runtime. Reusable for other themes: point it at a
// different template and give it another name.
//
//   swift Scripts/GeneratePagesTemplate.swift <input.pages> <TemplateName> <output.swift>
//
// Example:
//   swift Scripts/GeneratePagesTemplate.swift Empty.pages blank \
//       Sources/SwiftTextPages/Generated/BlankPagesTemplate.swift

func fail(_ message: String) -> Never {
	FileHandle.standardError.write(Data((message + "\n").utf8))
	exit(1)
}

let args = Array(CommandLine.arguments.dropFirst())
guard args.count == 3 else {
	fail("usage: GeneratePagesTemplate.swift <input.pages> <templateName> <output.swift>")
}
let inputPath = args[0]
let templateName = args[1]
let outputPath = args[2]

/// Runs a process and returns its stdout data.
func run(_ launchPath: String, _ arguments: [String]) -> Data {
	let process = Process()
	process.executableURL = URL(fileURLWithPath: launchPath)
	process.arguments = arguments
	let pipe = Pipe()
	process.standardOutput = pipe
	process.standardError = FileHandle.nullDevice
	do { try process.run() } catch { fail("failed to run \(launchPath): \(error)") }
	let data = pipe.fileHandleForReading.readDataToEndOfFile()
	process.waitUntilExit()
	return data
}

// Entry order matters (we re-zip in the same order), so read the archive listing.
let listing = String(decoding: run("/usr/bin/unzip", ["-Z1", inputPath]), as: UTF8.self)
let paths = listing.split(separator: "\n").map(String.init).filter { !$0.isEmpty && !$0.hasSuffix("/") }
guard !paths.isEmpty else { fail("no entries found in \(inputPath)") }

// Emit Swift. Each entry's base64 is chunked across lines to keep the source
// readable and the parser happy with very long literals.
var out = """
// Generated by Scripts/GeneratePagesTemplate.swift — DO NOT EDIT.
// Source template: \(URL(fileURLWithPath: inputPath).lastPathComponent)
//
// Embeds every package entry of a blank Pages document as base64 so the writer can
// assemble a valid .pages from scratch with no bundled resource.

extension PagesTemplate {
\t/// The built-in "\(templateName)" Pages template, captured from a default document.
\tstatic let \(templateName) = PagesTemplate(entries: [

"""

for path in paths {
	let bytes = run("/usr/bin/unzip", ["-p", inputPath, path])
	let base64 = bytes.base64EncodedString()
	// Split into ~120-char chunks concatenated with + so no single literal is huge.
	var chunks = [String]()
	var index = base64.startIndex
	while index < base64.endIndex {
		let end = base64.index(index, offsetBy: 16_000, limitedBy: base64.endIndex) ?? base64.endIndex
		chunks.append(String(base64[index..<end]))
		index = end
	}
	let literal = chunks.map { "\"\($0)\"" }.joined(separator: "\n\t\t\t+ ")
	out += "\t\tEntry(path: \"\(path)\", base64: \(literal)),\n"
}

out += "\t])\n}\n"

do {
	try FileManager.default.createDirectory(
		at: URL(fileURLWithPath: outputPath).deletingLastPathComponent(),
		withIntermediateDirectories: true
	)
	try out.write(toFile: outputPath, atomically: true, encoding: .utf8)
} catch {
	fail("failed to write \(outputPath): \(error)")
}
print("wrote \(outputPath): \(paths.count) entries from \(inputPath)")
